- src/main/java/org/ject/support/domain/review/controller/ReviewController.java
- src/main/java/org/ject/support/domain/review/dto/ReviewResponse.java
- src/main/java/org/ject/support/domain/review/entity/Review.java
- src/main/java/org/ject/support/domain/review/repository/ReviewQueryRepository.java
- src/main/java/org/ject/support/domain/review/repository/ReviewQueryRepositoryImpl.java
- src/main/java/org/ject/support/domain/review/repository/ReviewRepository.java
- src/main/java/org/ject/support/domain/review/service/ReviewService.java
- src/test/java/org/ject/support/domain/project/repository/ProjectQueryRepositoryTest.java
- src/test/java/org/ject/support/domain/review/repository/ReviewRepositoryTest.java
close #45 
- Review 엔티티에 title, description 컬럼 추가
- 프로젝트 후기 목록 조회 기능 구현
후기 목록을 조회할 때 크롤링한 제목과 본문 일부를 함께 전달하는 방향으로 구현했습니다. 이를 위해 Review 엔티티에 title과 description 컬럼을 추가했어요. 
자세한 내용은 노션을 참고해 주세요. 
https://www.notion.so/URL-1a562a893ac5804997c5f3bb8e1b8206?pvs=4
> 프로젝트 후기 목록 조회 기능 구현

- src/main/java/org/ject/support/domain/project/controller/ProjectController.java
- src/main/java/org/ject/support/domain/project/entity/Project.java
- src/main/java/org/ject/support/domain/project/repository/ProjectQueryRepository.java
- src/main/java/org/ject/support/domain/project/repository/ProjectQueryRepositoryImpl.java
- src/main/java/org/ject/support/domain/project/service/ProjectService.java
- src/test/java/org/ject/support/domain/project/repository/ProjectQueryRepositoryTest.java
close #55 
- 프로젝트 엔티티에 카테고리 컬럼 추가
- 프로젝트 목록 조회 API 파라미터에 카테고리 값 추가
- 해커톤 프로젝트 목록 조회 단위 테스트
> 프로젝트 엔티티에 카테고리 컬럼 추가

- src/main/java/org/ject/support/common/security/CustomUserDetails.java
- src/main/java/org/ject/support/common/security/config/SecurityConfig.java
- src/main/java/org/ject/support/common/security/jwt/JwtTokenProvider.java
- src/main/java/org/ject/support/domain/auth/AuthController.java
- src/main/java/org/ject/support/external/email/EmailController.java
- src/test/java/org/ject/support/common/security/CustomUserDetailsTest.java
- src/test/java/org/ject/support/common/security/config/SecurityConfigTest.java
- src/test/java/org/ject/support/common/security/jwt/JwtTokenProviderTest.java
- src/test/java/org/ject/support/domain/auth/AuthControllerTest.java
close #51 
- `RoleHierarchy` 설정
- 토큰에 `Role` 정상적으로 담기도록 기능 개선
- 테스트 코드 작성
https://oth3410.tistory.com/356
자세한 내용은 위 게시글을 참고해주세요. 각자 맡으신 API에 어노테이션을 달아주시면 됩니다.
아래는 예시입니다.
`@PreAuthorize("permitAll()")` - (비회원 포함) 모든 권한 접근 가능
`@PreAuthorize("hasRole('ROLE_TEMP')")` - 메서드 실행 전에 검증됨. TEMP 권한 이상만 통과됨
`@PostAuthorize("returnObject.email == authentication.email") // 리턴 객체의 이메일과 인증정보의 이메일 등을 비교가 가능함` - 메서드 실행 이후 검증됨. 추가 권한 확인이 필요할 때 사용
> Role Hierarchy를 사용한 인가 기능 구현

- src/main/java/org/ject/support/common/security/config/SecurityConfig.java
- src/main/resources/application-test.yml
close #71 
`SecurityConfig` 에 CORS 방지를 위한 백엔드 도메인을 허용했습니다.
> CORS 방지를 위한 허용 출처 추가

- src/main/java/org/ject/support/domain/file/controller/FileController.java
- src/main/java/org/ject/support/domain/file/dto/CreatePresignedUrlResponse.java
- src/main/java/org/ject/support/domain/file/dto/UploadFileRequest.java
- src/main/java/org/ject/support/domain/file/dto/UploadFileResponse.java
- src/main/java/org/ject/support/domain/file/exception/FileErrorCode.java
- src/main/java/org/ject/support/domain/file/exception/FileException.java
- src/main/java/org/ject/support/external/s3/S3Service.java
- src/test/java/org/ject/support/domain/file/controller/FileControllerTest.java
- src/test/java/org/ject/support/external/s3/S3ServiceTest.java
close #40 
- 이미지 업로드 API path 분리
- 구현된 API 모두 인가 처리
- 하나의 파일 업로드 API에서 포폴 전용 API 분리
- url 생성 시 content-type과 content-length 지정하는 코드 추가
url 생성 시 지정한 contentType이나 contentLength가 업로드한 파일의 메타데이터와 다를 경우 위 error가 발생하는 것까지 확인했습니다.
> 권한에 따라 pre-signed url api 분리 및 인가 처리

- src/main/java/org/ject/support/common/data/RestPage.java
- src/main/java/org/ject/support/common/data/redis/RedisConfig.java
- src/main/java/org/ject/support/domain/jectalk/controller/JectalkController.java
- src/main/java/org/ject/support/domain/jectalk/dto/JectalkResponse.java
- src/main/java/org/ject/support/domain/jectalk/entity/Jectalk.java
- src/main/java/org/ject/support/domain/jectalk/repository/JectalkQueryRepository.java
- src/main/java/org/ject/support/domain/jectalk/repository/JectalkQueryRepositoryImpl.java
- src/main/java/org/ject/support/domain/jectalk/service/JectalkService.java
- src/main/java/org/ject/support/domain/ministudy/controller/MiniStudyController.java
- src/main/java/org/ject/support/domain/ministudy/dto/MiniStudyResponse.java
- src/main/java/org/ject/support/domain/ministudy/entity/MiniStudy.java
- src/main/java/org/ject/support/domain/ministudy/repository/MiniStudyQueryRepository.java
- src/main/java/org/ject/support/domain/ministudy/repository/MiniStudyQueryRepositoryImpl.java
- src/main/java/org/ject/support/domain/ministudy/service/MiniStudyService.java
- src/main/java/org/ject/support/domain/project/dto/ProjectResponse.java
- src/main/java/org/ject/support/domain/project/repository/ProjectQueryRepository.java
- src/main/java/org/ject/support/domain/project/repository/ProjectQueryRepositoryImpl.java
- src/main/java/org/ject/support/domain/project/service/ProjectService.java
- src/main/java/org/ject/support/domain/review/controller/ReviewController.java
- src/main/java/org/ject/support/domain/review/dto/ReviewResponse.java
- src/main/java/org/ject/support/domain/review/entity/Review.java
- src/main/java/org/ject/support/domain/review/repository/ReviewQueryRepository.java
- src/main/java/org/ject/support/domain/review/repository/ReviewQueryRepositoryImpl.java
- src/main/java/org/ject/support/domain/review/service/ReviewService.java
- src/test/java/org/ject/support/domain/jectalk/repository/JectalkQueryRepositoryTest.java
- src/test/java/org/ject/support/domain/ministudy/repository/MiniStudyQueryRepositoryTest.java
- src/test/java/org/ject/support/domain/project/repository/ProjectQueryRepositoryTest.java
- src/test/java/org/ject/support/domain/review/repository/ReviewRepositoryTest.java
close #70 
- RestPage 클래스 구현
- Redis 캐시매니저 세팅
- 아래 API에 캐시 적용
- 프로젝트 목록 조회
- 프로젝트 상세 조회
- 프로젝트 후기 목록 조회
- 미니스터디 목록 조회
- 젝톡 목록 조회
- 프로젝트 목록 조회 응답 dto에 `description` 추가, `startDate`와 `endDate` 제거
- 프로젝트 후기 목록 조회 응답 dto에 `summary` 추가
- 젝톡, 미니스터디 엔티티와 응답 dto에 `summary` 추가
- 리뷰, 젝톡, 미니스터디 목록 조회 응답 dto에 `id` 추가
캐싱을 적용하였더니 아래와 같은 에러가 발생했습니다.
```
org.springframework.data.redis.serializer.SerializationException: Could not read JSON:Cannot construct instance of org.springframework.data.domain.PageImpl (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
at [Source: REDACTED (StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION disabled); line: 1, column: 46]
```
이는 `Page<T>`가 역직렬화되지 않아 발생한 것으로 확인했습니다.
따라서 직렬화/역직렬화가 가능하도록 RestPage 클래스를 …
> 캐시 적용 및 API 응답 필드 수정

- src/main/java/org/ject/support/domain/member/dto/TeamMemberNames.java
- src/test/java/org/ject/support/domain/member/repository/MemberQueryRepositoryTest.java
- src/test/java/org/ject/support/domain/project/service/ProjectServiceTest.java
close #98 
- 프로젝트 상세 조회 API 응답 필드명 변경(projectManagers -> productManagers)
> 프로젝트 상세 조회 API 응답 필드명 변경(projectManagers -> productManagers)

- src/main/java/org/ject/support/domain/auth/AuthController.java
- src/main/java/org/ject/support/domain/auth/AuthDto.java
- src/main/java/org/ject/support/domain/auth/AuthErrorCode.java
- src/main/java/org/ject/support/domain/auth/AuthService.java
- src/main/java/org/ject/support/domain/member/repository/MemberRepository.java
- src/test/java/org/ject/support/domain/auth/AuthControllerTest.java
- src/test/java/org/ject/support/domain/auth/AuthServiceTest.java
close #97 
- 핀번호 로그인 API 구현
- 회원 존재 여부 확인 API 구현
회원 존재 여부 확인 API의 도메인이 `member` 이어야 하는지 `auth` 이어야 하는지를 꽤 고민했는데,
해당 API는 로그인 과정과 직접적으로 연결되는 API이므로 `auth` 쪽에 두는 것이 더 적절하다고 생각했습니다. 프론트 입장에서도 사용성이 더 높고요.
> 핀번호 로그인 및 회원 존재 여부 확인 API 구현

- src/main/java/org/ject/support/common/exception/GlobalErrorCode.java
- src/main/java/org/ject/support/domain/auth/AuthController.java
- src/main/java/org/ject/support/domain/auth/AuthDto.java
- src/main/java/org/ject/support/domain/auth/AuthErrorCode.java
- src/main/java/org/ject/support/domain/auth/AuthService.java
- src/test/java/org/ject/support/domain/auth/AuthControllerTest.java
- src/test/java/org/ject/support/domain/auth/AuthServiceTest.java
- src/test/java/org/ject/support/domain/file/controller/FileControllerTest.java
- src/test/java/org/ject/support/testconfig/TestSecurityConfig.java
close #95 
- 리프레시 토큰 재발급 기능 구현
- `GlobalErrorCode` 에서 잘못된 에러코드 번호 수정
리프레시 토큰 재발급 시 발생하는 예외처리에 대한 에러코드를 Global에 둘지, Auth에 둘지를 조금 고민했습니다.
결론은, '리프레시 토큰'은 엑세스 토큰을 재발급 할 때만 쓰이므로, 전역적으로 사용되지 않는다 판단, Auth 도메인에 속하는게 맞다고 생각했습니다.
> 엑세스 토큰 재발급 기능 구현

- src/main/java/org/ject/support/domain/file/dto/UploadFileResponse.java
- src/main/java/org/ject/support/external/s3/S3Service.java
- src/test/java/org/ject/support/external/s3/S3ServiceTest.java
close #128 
- UploadFileResponse의 fileName 필드를 cdnUrl로 변경
- 테스트코드 수정
> pre-signed url 발급 완료 시 cdn url 전달하도록 변경

- src/main/java/org/ject/support/domain/project/dto/ProjectDetailResponse.java
- src/main/java/org/ject/support/domain/project/entity/Project.java
- src/test/java/org/ject/support/domain/project/service/ProjectServiceTest.java
close #131 
- 프로젝트의 기술 스택을 쉼표로 구분하여 조회하도록 구현
- 프로젝트 상세 조회 시 기술 스택을 배열 형태로 반환하는지 검증
> 프로젝트의 기술 스택을 쉼표로 구분하여 조회하도록 구현

- src/main/java/org/ject/support/common/security/jwt/JwtAuthenticationFilter.java
- src/main/java/org/ject/support/common/security/jwt/JwtExceptionHandlerFilter.java
- src/main/java/org/ject/support/domain/member/Role.java
close #125 
- `JwtExceptionHandlerFilter` 에서 `Exception e` 로 필터 단에서 모든 예외를 잡는 부분을 `doFilter()` 사용 시 필요한 `ServletException e` 예외를 잡도록 수정 -> 토큰 사용시 시큐리티와 관계 없는 예외가 필터 단에서 잡히지 않도록 수정됨
- 임시 회원 가입을 위한 `verificationToken` 생성 시, `JwtAuthenticationFilter` 에서 `String` 대신 `CustomUserDetails` 객체를 생성하도록 수정
> Security 필터 예외처리 수정

- build.gradle
close #113 
- 모니터링 툴(Grafana, Loki, Prometheus, Promtail) 사용을 위한 의존성 추가
- `spring-boot-starter-actuator`
- `micrometer-registry-prometheus` 
- 승인 후 s3에 존재하는 prod.yml 에 아래 내용이 추가될 예정입니다.
```yml
management:
endpoints:
web:
exposure:
include: prometheus, health, info
prometheus:
metrics:
export:
enabled: true
```
> 모니터링 툴 사용을 위한 actuator, prometheus 의존성 추가

- src/main/java/org/ject/support/domain/recruit/domain/Recruit.java
- src/main/java/org/ject/support/domain/recruit/repository/QuestionQueryRepository.java
- src/main/java/org/ject/support/domain/recruit/repository/QuestionQueryRepositoryImpl.java
- src/main/java/org/ject/support/domain/recruit/repository/RecruitQueryRepository.java
- src/main/java/org/ject/support/domain/recruit/repository/RecruitQueryRepositoryImpl.java
- src/main/java/org/ject/support/domain/recruit/repository/RecruitRepository.java
- src/main/java/org/ject/support/domain/recruit/service/AccessPeriodInitializer.java
- src/main/java/org/ject/support/domain/recruit/service/ApplyService.java
- src/main/java/org/ject/support/domain/recruit/service/QuestionService.java
- src/main/java/org/ject/support/domain/recruit/service/RecruitScheduleService.java
- src/test/java/org/ject/support/domain/file/controller/FileControllerTest.java
- src/test/java/org/ject/support/domain/recruit/controller/ApplyControllerTest.java
- src/test/java/org/ject/support/domain/recruit/domain/RecruitTest.java
- src/test/java/org/ject/support/domain/recruit/repository/QuestionQueryRepositoryTest.java
- src/test/java/org/ject/support/domain/recruit/service/RecruitScheduleServiceTest.java
close #149 
- Recruit의 startDate와 endDate의 타입을 LocalDateTime으로 변경
- 타입 변경으로 인한 RecruitScheduleServiceTest#test_schedule_end_date_of_recruit 실패 문제 해결
- Recruit의 isRecruitingPeriod와 isInvalidQuesionId 메서드 단위 테스트
Recruit 엔티티의 시작/마감일을 LocalDateTime으로 변경 시, RecruitScheduleServiceTest#test_schedule_end_date_of_recruit 테스트가 실패했습니다.
기존 LocalDate 타입의 경우 isBefore 메서드가 같은 날짜를 포함하지 않아, Recruit의 isRecruitingPeriod 조건에 걸려 이벤트가 발행되지 않았습니다.
하지만 LocalDateTime의 isBefore 메서드는 시분초까지 다루기 때문에, 1초라도 과거라면 isBefore 메서드는 true를 반환합니다. 
이로 인해 이벤트가 정상 발행되는데, 테스트 코드에서 handleRecruitOpened 메서드를 또 한 번 호출해서 verify가 실패한 것입니다.
따라서, handleRecruitOpened 메서드를 호출하는 부분을 제거했습니다.
> Recruit의 기간 필드의 타입을 LocalDateTime으로 변경

- src/main/java/org/ject/support/common/data/redis/RedisConfig.java
- src/main/java/org/ject/support/domain/recruit/service/QuestionService.java
- src/test/java/org/ject/support/domain/recruit/controller/QuestionControllerTest.java
close #141 
- redis 캐시 기본 ttl을 1일로 변경
- 지원서 문항 조회 기능에 캐싱 적용
> 지원서 문항 조회 기능에 캐싱 적용

- src/main/java/org/ject/support/domain/auth/AuthController.java
- src/main/java/org/ject/support/domain/auth/AuthDto.java
- src/main/java/org/ject/support/domain/auth/AuthService.java
- src/main/java/org/ject/support/external/email/EmailAuthService.java
- src/main/java/org/ject/support/external/email/EmailController.java
- src/main/java/org/ject/support/external/email/EmailTemplate.java
- src/test/java/org/ject/support/domain/auth/AuthControllerTest.java
- src/test/java/org/ject/support/domain/auth/AuthServiceTest.java
close #156
- 인증 이메일 발송 시 기존 구현 되어 있던 EmailTemplate 사용
- 인증 번호 검증 시 파라미터의 EmailTemplate에 따라 다른 토큰 발급하도록 구현
인증 번호 검증 부분을 조금 더 확장 가능하게 할 수 있을 거 같긴 합니다. 그런데 아직 기획 측면에서 예정된 확장 가능성이 없다보니, 고민이 많이 되었습니다.
전략 패턴을 도입하자니 배보다 배꼽이 더 커지는 것 같고, switch문은 좀.. 짜치다고 생각했습니다.
그래서 그냥 조건문으로만 이메일 템플릿을 검증하도록 구현했습니다. 사실 '인증 번호 발송' 메일은 그 범주가 되게 제한적이니까요.
'어디까지 확장 가능성을 열어 놓을 것인가' - '정말 필요한 구현인가' 의 트레이드 오프 사이에서 꽤 고민했습니다. 
좋은 의견이 있으시면 알려주세요!
> 핀 재설정 시 이메일 발송 및 인증 번호 검증 기능 구현

- build.gradle
- src/main/resources/application-test.yml
- src/main/resources/logs/logback-local.xml
- src/main/resources/logs/logback-prod.xml
close #165 
- 운영환경별 (local, prod) logback.xml 파일 작성
- CloudWatch 전용 IAM 관련 키 prod.yml 에 작성
- 로컬에서 그라파나 볼 수 있게 설정
> Logback + CloudWatch 세팅

- src/main/java/org/ject/support/common/security/jwt/JwtCookieProvider.java
close #186
- 프론트 https 배포 완료에 따른, 쿠키 발급 시 `setSecure` 설정 활성화
- 쿠키 발급 로직 메서드화
> 쿠키 발급 시 setSecure 설정 활성화

- src/main/java/org/ject/support/common/security/CustomSuccessHandler.java
- src/main/java/org/ject/support/common/security/jwt/JwtAuthenticationFilter.java
- src/main/java/org/ject/support/common/security/jwt/JwtCookieProvider.java
- src/main/java/org/ject/support/common/security/jwt/JwtTokenProvider.java
- src/main/java/org/ject/support/domain/auth/AuthController.java
- src/main/java/org/ject/support/domain/auth/AuthService.java
- src/main/java/org/ject/support/domain/auth/AuthVerificationResult.java
- src/main/java/org/ject/support/external/email/MailErrorCode.java
- src/test/java/org/ject/support/common/security/jwt/JwtTokenProviderTest.java
- src/test/java/org/ject/support/domain/auth/AuthControllerTest.java
- src/test/java/org/ject/support/domain/auth/AuthServiceTest.java
close #174 
close #175
- `verificationToken` 및 `accessToken` 재발급시에도 쿠키에 토큰 발급하도록 토큰 발급 방식 일관성 확보
- 클라이언트의 API 요청 시 Authorizatoin 헤더 대신 쿠키에서 토큰 가져오도록 토큰 확인 방식 일관성 확보
- `CustomSuccessHandler` 를 통해 쿠키가 발급되도록 개선
- 인증 검증 결과 래퍼 클래스 `AuthVerificationResult` 작성
`CustomSuccessHandler`는 스프링 시큐리티 기본 로그인시에만 동작하고 있어서 쿠키가 정상적으로 발급 되지 않는 이슈가 있었습니다.
또한, 쿠키 발급 시 `HttpOnly` 설정이 켜져 있어서 프론트에서 쿠키를 열어볼 수 없어 Authorization 헤더로 토큰을 보낼 수 없는 이슈도 있었습니다. 보안성을 위해 `HttpOnly` 설정을 사용하는 건 불가피하므로, 서버에서 쿠키에 저장된 토큰을 가져오는 방식으로 토큰 수용 방식 또한 개선했습니다.
서블렛 리퀘스트, 리스폰스가 서비스 레이어까지 침투하지 않게 하기 위해 불가피하게 `AuthController`에 조건부 응답 처리를 구현했습니다. 전략 패턴, 팩토리 패턴을 도입하는 방법도 있으나, 해당 부분은 서비스 로직을 처리하는 조건문이 아닌 어떤 메서드를 호출할 지에 대한 조건문이므로 상관 없다고 판단했습니다. 그리고 무엇보다 빠른 개선이 필요한 작업이므로 직관적이면서도 빠르게 해결할 수 있는 방법으로 구현했습니다.
> 토큰을 쿠키에서 가져오도록 인증 로직 수정

- src/main/java/org/ject/support/domain/auth/AuthController.java
- src/main/java/org/ject/support/domain/auth/AuthDto.java
- src/main/java/org/ject/support/domain/member/controller/MemberController.java
- src/main/java/org/ject/support/domain/member/dto/MemberDto.java
- src/test/java/org/ject/support/domain/auth/AuthServiceTest.java
close #183 
클라이언트에서는 인증 관련 API 호출 후 반환되는 `SUCCESS` status를 통해 api 호출 여부를 검증하고 있습니다.
기존에는 서버에서 Response로 토큰 값을 제공해줬는데, 이제 클라이언트에 직접 body response로 토큰을 제공하지 않아서 명시적으로 응답을 제공하기 위해 true를 반환하도록 수정했습니다. (void 나 null로 API 응답 반환시에는 전역적으로 적용되는 `ApiResponse`가 적용되지 않습니다.)
> 인증 API 호출 완료 시 클라이언트에 명시적인 응답 반환

- src/main/java/org/ject/support/domain/recruit/controller/QuestionController.java
- src/main/java/org/ject/support/domain/recruit/controller/SemesterController.java
- src/main/java/org/ject/support/domain/recruit/dto/QuestionResponses.java
- src/main/java/org/ject/support/domain/recruit/dto/SemesterResponse.java
- src/main/java/org/ject/support/domain/recruit/dto/SemesterResponses.java
- src/main/java/org/ject/support/domain/recruit/service/QuestionService.java
- src/main/java/org/ject/support/domain/recruit/service/SemesterInquiryService.java
- src/main/java/org/ject/support/domain/recruit/service/SemesterInquiryUsecase.java
close #179 
- List<SemesterResponse> 타입 객체를 wrapper 클래스로 감싸도록 수정
- List<QuestionResponse> 타입 객체를 wrapper 클래스로 감싸도록 수정
> 기수 목록 조회 시 redis 역직렬화 이슈 해결

- src/main/java/org/ject/support/domain/auth/AuthService.java
- src/main/java/org/ject/support/domain/auth/AuthVerificationResult.java
- src/main/java/org/ject/support/external/email/EmailTemplate.java
- src/main/resources/templates/email-template.html
- src/test/java/org/ject/support/domain/auth/AuthControllerTest.java
- src/test/java/org/ject/support/domain/auth/AuthServiceTest.java
close #181 
- 이메일 HTML 템플릿을 수정했습니다.
- SMTP 공급자 수정은 여러 이슈 때문에 현재는 불가합니다. (+다음 메일이 지메일에 비해 발송이 너무 느린 문제도 있습니다.)
지메일
네이버
> 인증 코드 이메일 템플릿 수정

- src/main/java/org/ject/support/common/exception/GlobalErrorCode.java
- src/main/java/org/ject/support/common/util/PeriodAccessible.java
- src/main/java/org/ject/support/domain/recruit/domain/Recruit.java
- src/main/java/org/ject/support/domain/recruit/domain/RecruitEntityListener.java
- src/main/java/org/ject/support/domain/recruit/dto/Constants.java
- src/main/java/org/ject/support/domain/recruit/dto/RecruitOpenedEvent.java
- src/main/java/org/ject/support/domain/recruit/dto/RecruitRegisterRequest.java
- src/main/java/org/ject/support/domain/recruit/dto/RecruitSavedEvent.java
- src/main/java/org/ject/support/domain/recruit/dto/RecruitUpdateRequest.java
- src/main/java/org/ject/support/domain/recruit/repository/RecruitQueryRepository.java
- src/main/java/org/ject/support/domain/recruit/repository/RecruitQueryRepositoryImpl.java
- src/main/java/org/ject/support/domain/recruit/repository/RecruitRepository.java
- src/main/java/org/ject/support/domain/recruit/service/AccessPeriodInitializer.java
- src/main/java/org/ject/support/domain/recruit/service/AccessPeriodVerificator.java
- src/main/java/org/ject/support/domain/recruit/service/AccessPeriodVerifier.java
- src/main/java/org/ject/support/domain/recruit/service/ApplyService.java
- src/main/java/org/ject/support/domain/recruit/service/RecruitFlagService.java
- src/main/java/org/ject/support/domain/recruit/service/RecruitSavedEventHandler.java
- src/main/java/org/ject/support/domain/recruit/service/RecruitScheduleService.java
- src/main/java/org/ject/support/external/s3/S3Service.java
- src/test/java/org/ject/support/domain/file/controller/FileControllerTest.java
- src/test/java/org/ject/support/domain/recruit/controller/QuestionControllerTest.java
- src/test/java/org/ject/support/domain/recruit/service/AccessPeriodInitializerTest.java
- src/test/java/org/ject/support/domain/recruit/service/AccessPeriodVerificatorTest.java
- src/test/java/org/ject/support/domain/recruit/service/AccessPeriodVerifierTest.java
- src/test/java/org/ject/support/domain/recruit/service/RecruitFlagServiceTest.java
- src/test/java/org/ject/support/domain/recruit/service/RecruitSavedEventHandlerTest.java
- src/test/java/org/ject/support/domain/recruit/service/RecruitScheduleServiceTest.java
- src/test/java/org/ject/support/domain/recruit/service/RecruitServiceTest.java
- src/test/java/org/ject/support/testconfig/ApplicationPeriodTest.java
close #188 
- Recruit 등록/수정 dto의 startDate에 있는 `@Future` 제거
- 모집 여부에 따른 접근 제한 시 사용하는 플래그를 PERIOD_FLAG에서 RECRUIT_FLAG로 수정
- Recruit의 isClosed 필드 제거
> recruit flag 관리 로직 개선

- src/main/java/org/ject/support/domain/member/exception/MemberErrorCode.java
- src/main/java/org/ject/support/domain/member/service/MemberService.java
- src/test/java/org/ject/support/domain/member/controller/MemberControllerTest.java
- src/test/java/org/ject/support/domain/member/service/MemberServiceTest.java
close #202
- 핀번호 동일 검증 로직 제거
- 관련 에러 코드 제거
- 테스트 코드 수정
> 핀번호 수정 시 이전과 동일한 핀번호도 허용하도록 수정
